/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <QDebug>
#include <jniimplement.h>

/* Header for class com_hungkv_loadlibrary_JniMessenger */

#ifndef _Included_com_hungkv_loadlibrary_JniMessenger
#define _Included_com_hungkv_loadlibrary_JniMessenger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hungkv_loadlibrary_JniMessenger
 * Method:    callFromJava
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hungkv_loadlibrary_JniMessenger_callFromJava
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
